# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85980885474c716043ce682db22b20969a00b4955cee9405aef9f31c5d545a608c1b6805370bc98534acff5d0ee3b70985803331cb28af7092ccd586d29fde53

test:
  secret_key_base: 2e10affa860644ec7695caf1fbd6331a19c230a19646c73bdc53e64bc433cf82f4b07b6cb0d65167aa86eeeed89819d646fe660ae5771a70db7a3145bee4e79a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
